# version: "3.9"

services:
  fastapi-server:
    build: ./central-server
    container_name: vigilhawk-central-server
    ports:
      - "8000:8000"
    volumes:
      - ./hls_data:/tmp/hls
    depends_on:
      - mongo
      - rtsp-server
    environment:
      MONGO_URI: ${MONGO_URI}
      SECRET_KEY: ${SECRET_KEY}
    restart: unless-stopped

  detection-server:
    build: ./detection-server
    container_name: vigilhawk-detection-server
    ports:
      - "8001:8001"
    depends_on:
      - mongo
    volumes:
      - ./hls:/app/hls
    environment:
      MONGO_URI: ${MONGO_URI}
    restart: unless-stopped

  react-server:
    build: ./react-server
    container_name: vigilhawk-react
    volumes:
      # - ./dist:/usr/share/nginx/html
      - ./react-server/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8082:80"
    depends_on:
      - fastapi-server
      - rtsp-server
    restart: unless-stopped

  nats:
    image: nats:2.10
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"  # monitoring UI
    command: ["-js"]  # enable JetStream
    restart: always


  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  rtsp-server:
    image: bluenviron/mediamtx
    ports:
      - "8554:8554"
    restart: unless-stopped
    volumes:
      - ./config/mediamtx.yml:/mediamtx.yml:ro
    #command: ["mediamtx", "/mediamtx.yml"]
networks:
  mynet:
    driver: bridge