logLevel: info
logDestinations: [stdout]

authMethod: internal

authInternalUsers:
  - user: any
    pass:
    ips: []
    permissions:
      - action: publish
        # path: 6935784455d6753646294c8e
      - action: read
        # path: 6935784455d6753646294c8e
      - action: playback
        # path: 6935784455d6753646294c8e
paths:
  all_others:

hls: yes
# Address of the HLS listener.
hlsAddress: :8888
# Enable TLS/HTTPS on the HLS server.
# This is required for Low-Latency HLS.
hlsEncryption: no

hlsAllowOrigins: ['*']

hlsDirectory: '/app/hls'

api: no
metrics: no
pprof: no

rtsp: yes
rtspAddress: :8554
rtspTransports: [tcp, udp]
rtspEncryption: "no"
rtspAuthMethods: [basic]

rtmp: no
webrtc:
  listenAddress: :8889
  iceServers:
    - urls: [stun:stun.l.google.com:19302]